import Head from "next/head";
import Tasks from "../components/table/Tasks";
import { Form } from "../components/Form";
import { Toaster } from "react-hot-toast";
import { useSelector, useDispatch } from "react-redux/";
import { toggleChangeAction } from "../redux/reducer";

export default function Home() {
  const visible = useSelector((state) => state.app.client.toggleForm);
  const dispatch = useDispatch();
  const toggleForm = () => {
    dispatch(toggleChangeAction());
  };
  return (
    <section>
      <Head>
        <title>Let's Do</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
      <main className="px-4 md:px-10 py-6">
        <Toaster
          position="top-right"
          duration="3000"
          toastOptions={{
            success: {
              theme: {
                primary: "blue",
              },
            },
          }}
        ></Toaster>
        <h1 className="text-2xl md:text-5xl font-bold text-white text-center py-5">
          Let's Do ✍🏼
        </h1>

        <div className="flex flex-col md:flex-row gap-10 w-full mt-10">
          <div className="w-full md:w-1/4">
            <div className="container mx-auto flex flex-col md:flex-row justify-between py-5">
              <div className="left flex gap-3">
                <button
                  className="flex bg-zinc-800 text-slate-200 hover:text-white px-4 py-2 text-xl rounded-md"
                  onClick={toggleForm}
                >
                  Add Task
                </button>
              </div>
            </div>

            {/* form */}
            {visible ? <Form /> : null}
          </div>

          {/* table */}
          <div className="w-full md:w-3/4">
            <Tasks />
          </div>
        </div>
      </main>
    </section>
  );
}
